const badWords = [
  // Palabras fuertes generales y variantes
  "puta",
  "puto",
  "putas",
  "putos",
  "putita",
  "putito",
  "putitas",
  "putitos",
  "mierda",
  "mierdas",
  "mierdero",
  "mierdera",
  "mierderos",
  "mierderas",
  "mierda seca",
  "mierda fresca",
  "cabron",
  "cabrona",
  "cabrones",
  "cabronas",
  "cabroncito",
  "cabroncita",
  "cabroncitos",
  "cabroncitas",
  "pendejo",
  "pendeja",
  "pendejos",
  "pendejas",
  "pendejito",
  "pendejita",
  "pendejitos",
  "pendejitas",
  "pendejada",
  "pendejadas",
  "coño",
  "coños",
  "joder",
  "jodido",
  "jodida",
  "jodidos",
  "jodidas",
  "gilipollas",
  "gilipollos",
  "imbécil",
  "imbéciles",
  "estúpido",
  "estúpida",
  "estúpidos",
  "estúpidas",
  "idiota",
  "idiotas",
  "idiotez",
  "idioteces",
  // Mexicanismos y variantes
  "chingar",
  "chingada",
  "chingado",
  "chingados",
  "chingada",
  "chingadas",
  "chingón",
  "chingona",
  "chingones",
  "chingonas",
  "chingadera",
  "chingaderas",
  "verga",
  "vergas",
  "vergazo",
  "vergazos",
  "pinche",
  "pinches",
  "pinchito",
  "pinchitos",
  "culero",
  "culera",
  "culeros",
  "culeras",
  "culito",
  "culitos",
  "culazo",
  "culazos",
  "madre",
  "madres",
  "madrear",
  "madreador",
  "madreadora",
  "madreadoras",
  "madreador",
  "madreadoras",
  "pito",
  "pitos",
  "naco",
  "naca",
  "nacos",
  "nacas",
  "zorra",
  "zorras",
  "zorrilla",
  "zorrillas",
  "perra",
  "perras",
  "perro",
  "perros",
  "perrita",
  "perritas",
  "perrito",
  "perritos",
  "mamón",
  "mamona",
  "mamones",
  "mamonas",
  "estupidez",
  "estupideces",
  "cagada",
  "cagadas",
  "cagar",
  "cagado",
  "cagados",
  "cagada",
  "cagadas",
  "maricón",
  "maricona",
  "maricones",
  "mariconas",
  "joto",
  "jota",
  "jotos",
  "jotas",
  "putazo",
  "putazos",
  "chingadazo",
  "chingadazos",
  "pendejazo",
  "pendejazos",
  // Frases y compuestos
  "chingada madre",
  "chingadas madres",
  "hijo de puta",
  "hija de puta",
  "hijos de puta",
  "hijas de puta",
  "hijo de perra",
  "hija de perra",
  "hijos de perra",
  "hijas de perra",
  "hijo de la chingada",
  "hijos de la chingada",
  "vete a la verga",
  "vete al carajo",
  "vete a la chingada",
  "vete a la mierda",
  "pinche madre",
  "pinches madres",
  "puta madre",
  "putas madres",
  "chingada madre",
  "chingadas madres",
  "malparido",
  "malparida",
  "malparidos",
  "malparidas",
  // Diminutivos y variantes
  "me vale madre",
  "me vale madres",
  "me vale verga",
  "me vale vergas",
  "me vale pito",
  "me vale pitos",
  "a la verga",
  "a las vergas",
  "a la chingada",
  "a las chingadas",
  "a la mierda",
  "a las mierdas",
  "a la madre",
  "a las madres",
  "a la fregada",
  "a las fregadas",
  // ...puedes seguir ampliando según necesidad
];

export function censorBadWords(text: string): string {
  let censored = text;
  for (const word of badWords) {
    const regex = new RegExp(
      `\\b${word.replace(/([.*+?^=!:${}()|[\]\/\\])/g, "\\$1")}\\b`,
      "gi"
    );
    censored = censored.replace(regex, "*".repeat(word.length));
  }
  return censored;
}
