const badWords = [
  // Palabras fuertes generales
  "puta",
  "puto",
  "mierda",
  "cabron",
  "cabrón",
  "pendejo",
  "pendeja",
  "coño",
  "joder",
  "gilipollas",
  "imbécil",
  "estúpido",
  "idiota",
  // Mexicanismos y variantes
  "chingar",
  "chingada",
  "chingado",
  "chingados",
  "chingar",
  "chingón",
  "chingona",
  "chingones",
  "chingonas",
  "chingadera",
  "chingaderas",
  "verga",
  "vergas",
  "pinche",
  "pinches",
  "culero",
  "culera",
  "culeros",
  "culeras",
  "madre",
  "madres",
  "madrear",
  "madreador",
  "madreadora",
  "pito",
  "pitos",
  "naco",
  "naca",
  "nacos",
  "nacas",
  "zorra",
  "zorras",
  "perra",
  "perras",
  "perro",
  "perros",
  "mamón",
  "mamona",
  "mamones",
  "mamonas",
  "mierdero",
  "mierdera",
  "mierderos",
  "mierderas",
  "pendejada",
  "pendejadas",
  "estupidez",
  "estupideces",
  "idiotez",
  "idioteces",
  "culito",
  "culitos",
  "cagada",
  "cagadas",
  "cagar",
  "cagado",
  "cagados",
  "cagada",
  "cagadas",
  "cabrón",
  "cabrona",
  "cabrones",
  "cabronas",
  "maricón",
  "maricona",
  "maricones",
  "mariconas",
  "joto",
  "jota",
  "jotos",
  "jotas",
  "putazo",
  "putazos",
  "chingadazo",
  "chingadazos",
  "pendejazo",
  "pendejazos",
  "culazo",
  "culazos",
  "vergazo",
  "vergazos",
  "madrazo",
  "madrazos",
  "chingada madre",
  "hijo de puta",
  "hija de puta",
  "hijo de perra",
  "hija de perra",
  "hijo de la chingada",
  "vete a la verga",
  "vete al carajo",
  "vete a la chingada",
  "vete a la mierda",
  "pinche madre",
  "puta madre",
  "chingada madre",
  "malparido",
  "malparida",
  "malparidos",
  "malparidas",
  "mierda seca",
  "mierda fresca",
  // Diminutivos y variantes
  "cabroncito",
  "cabroncita",
  "pendejito",
  "pendejita",
  "putita",
  "putito",
  "culito",
  "culita",
  "zorrilla",
  "perrita",
  "perrito",
  // Frases y compuestos
  "me vale madre",
  "me vale verga",
  "me vale pito",
  "a la verga",
  "a la chingada",
  "a la mierda",
  "a la madre",
  "a la fregada",
  // ...puedes seguir ampliando según necesidad
];

export function censorBadWords(text: string): string {
  let censored = text;
  for (const word of badWords) {
    const regex = new RegExp(
      `\\b${word.replace(/([.*+?^=!:${}()|[\]\/\\])/g, "\\$1")}\\b`,
      "gi"
    );
    censored = censored.replace(regex, "*".repeat(word.length));
  }
  return censored;
}
