import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    components: "src/components/index.ts",
    components4: "src/components4/index.ts",
    images: "src/images/index.ts",
    generate: "src/generate.ts",
    generateDocument: "src/generateDocument.ts",
    refine: "src/refine.ts",
    deploy: "src/deploy.ts",
    directions: "src/directions.ts",
    buildHtmlV4: "src/buildHtmlV4.ts",
    grapesToSections: "src/grapesToSections.ts",
    document: "src/document/index.ts",
    "hooks/useThumbnailCapture": "src/hooks/useThumbnailCapture.ts",
  },
  format: ["esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  external: [
    "react",
    "react-dom",
    "ai",
    "@ai-sdk/anthropic",
    "@ai-sdk/openai",
    "@codemirror/lang-html",
    "@codemirror/state",
    "@codemirror/theme-one-dark",
    "@codemirror/view",
    "@codemirror/commands",
    "@codemirror/search",
    "@codemirror/language",
    "@codemirror/autocomplete",
    "react-icons",
    "zod",
    "nanoid",
    "grapesjs",
    "tailwind-merge",
  ],
  // @ts-expect-error jsx option works at runtime but is not in tsup types
  jsx: "automatic",
});
