/**
 * Formmy Partner provisioning (EasyBits side) — connect a user's WhatsApp
 * Business (WABA) number to their FleetAgent WITHOUT the user having a Formmy account.
 *
 * Split of responsibilities (mirrors ~/agenda's Denik integration, but EasyBits
 * is the `easybits` partner instead of `denik`):
 *   - EasyBits opens Formmy's hosted Embedded Signup popup (Formmy holds the Meta
 *     App Secret + SDK) and captures `{ code, phoneNumberId, wabaId }`.
 *   - Formmy does code→token, registers the WABA, and creates its gateway rows
 *     (Agent shell + Channel + Integration) pointing `externalAgentUrl` at THIS
 *     fleetAgent's /waba endpoint. Returns `{ integrationId, phoneNumber }`.
 *   - This fleetAgent (the EasyBits fleet) is what answers the messages.
 *
 * Auth to Formmy = HMAC-SHA256 over `${timestamp}.${rawJsonBody}` with the
 * shared partner secret FORMMY_PARTNER_SECRET_EASYBITS, plus an `X-Partner-Id:
 * easybits` header so Formmy's partner registry resolves OUR secret + owner.
 */
import { createHmac, randomBytes } from "node:crypto";

const PARTNER_ID = "easybits";

function getFormmyBaseUrl(): string {
  return (process.env.FORMMY_BASE_URL || "https://www.formmy.app").replace(/\/$/, "");
}

function getPartnerSecret(): string {
  const secret = process.env.FORMMY_PARTNER_SECRET_EASYBITS;
  if (!secret) throw new Error("FORMMY_PARTNER_SECRET_EASYBITS not set");
  return secret;
}

/** Channel secret per integration, shared EasyBits↔Formmy↔fleetAgent. */
export function generateChannelSecret(): string {
  return randomBytes(24).toString("hex");
}

/**
 * Build the signed Formmy Embedded Signup popup URL. Formmy verifies the
 * timestamp + signature + opener `origin` against the easybits partner's
 * allowedOrigins before serving the popup.
 *
 *   sig = HMAC-SHA256(`${ts}.${origin}`, FORMMY_PARTNER_SECRET_EASYBITS)
 *
 * `origin` is EasyBits' own origin (the targetOrigin the popup posts back to).
 */
export function buildPopupUrl(origin: string): string {
  const ts = Math.floor(Date.now() / 1000).toString();
  const sig = createHmac("sha256", getPartnerSecret()).update(`${ts}.${origin}`).digest("hex");
  return `${getFormmyBaseUrl()}/partners/connect?ts=${ts}&o=${encodeURIComponent(
    origin
  )}&sig=${sig}&p=${PARTNER_ID}`;
}

export type FormmyProvisionParams = {
  /** `code` from Meta's Embedded Signup. */
  code: string;
  /** Phone Number ID reported by the WA_EMBEDDED_SIGNUP event. */
  phoneNumberId: string;
  /** WABA ID reported by the WA_EMBEDDED_SIGNUP event. */
  wabaId: string;
  /** Owner email (identifies the integration in Formmy). */
  email: string;
  /** External agent URL (this fleetAgent's /waba endpoint) that answers messages. */
  externalAgentUrl: string;
  /** Channel secret generated by EasyBits, propagated to Formmy + the fleetAgent. */
  channelSecret: string;
};

export type FormmyProvisionResult = {
  integrationId: string;
  phoneNumber: string;
};

/**
 * POST ${FORMMY_BASE_URL}/api/v1/partners/whatsapp/provision (HMAC-signed,
 * X-Partner-Id: easybits). Formmy does code→token, registers the WABA and
 * returns the integration.
 */
export async function provisionFormmyWhatsApp(
  params: FormmyProvisionParams
): Promise<FormmyProvisionResult> {
  const rawBody = JSON.stringify({
    code: params.code,
    phoneNumberId: params.phoneNumberId,
    wabaId: params.wabaId,
    email: params.email,
    externalAgentUrl: params.externalAgentUrl,
    channelSecret: params.channelSecret,
  });

  const timestamp = Math.floor(Date.now() / 1000).toString();
  const signature = createHmac("sha256", getPartnerSecret())
    .update(`${timestamp}.${rawBody}`)
    .digest("hex");

  const res = await fetch(`${getFormmyBaseUrl()}/api/v1/partners/whatsapp/provision`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-Partner-Id": PARTNER_ID,
      "X-Partner-Timestamp": timestamp,
      "X-Partner-Signature": signature,
    },
    body: rawBody,
  });

  if (!res.ok) {
    const body = await res.text().catch(() => "");
    throw new Error(`Formmy provision failed (${res.status}): ${body}`);
  }

  const out = (await res.json().catch(() => ({}))) as Partial<FormmyProvisionResult>;
  if (!out.integrationId) {
    throw new Error("Formmy provision: missing integrationId in response");
  }
  return { integrationId: out.integrationId, phoneNumber: out.phoneNumber ?? "" };
}
