// La ayuda en español: cada texto de la ayuda en inglés (resúmenes, grupos, descripciones de
// flags y comentarios de los ejemplos) → su traducción. help.ts la usa con LANG=es_*; el test
// help.test.ts falla si un texto de la ayuda no tiene traducción aquí (paridad).
export const HELP_ES: Record<string, string> = {
  "Account": "Cuenta",
  "Sign in with your browser (or save an API key)": "Entra con tu navegador (o guarda una API key)",
  "Sign in with your browser (OAuth2 + PKCE), or save an API key instead": "Entra con tu navegador (OAuth2 + PKCE), o guarda una API key en su lugar",
  "Only print the sign-in URL (e.g. for an agent to relay it)": "Sólo imprime la URL para entrar (p. ej. para que un agente te la pase)",
  "Read an API key from stdin instead of the browser (same as -)": "Lee una API key por stdin en vez del navegador (igual que -)",
  "opens the browser; waits for you": "abre el navegador y te espera",
  "agents: prints {\"event\":\"login_url\"} first": "agentes: primero imprime {\"event\":\"login_url\"}",
  "API key from stdin (validated first)": "API key por stdin (se valida antes)",
  "CI/agents: the env var needs no login at all": "CI/agentes: con la variable no hace falta login",
  "Forget the saved session and API key": "Olvida la sesión y la API key guardadas",
  "Remove the browser session and the API key from ~/.easybitsrc": "Quita la sesión del navegador y la API key de ~/.easybitsrc",
  "Show which account and credential the CLI is using": "Muestra qué cuenta y qué credencial usa el CLI",
  "Show the account email and where the credential comes from": "Muestra el correo de la cuenta y de dónde sale la credencial",
  "Check the CLI setup: Node, version, credential, API; exits 1 on a problem": "Revisa el CLI: Node, versión, credencial y API; sale con 1 si hay un problema",
  "Check Node, the CLI version, your credential and the API; exits 1 on a problem": "Revisa Node, la versión del CLI, tu credencial y la API; sale con 1 si hay un problema",
  "one agent": "un agente",
  "Show your plan, storage and resource counts": "Muestra tu plan, almacenamiento y cuántos recursos tienes",
  "Compute": "Cómputo",
  "Firecracker microVMs (alias: sb)": "MicroVMs Firecracker (alias: sb)",
  "List your sandboxes": "Enlista tus sandboxes",
  "Create a sandbox and wait until it is running": "Crea un sandbox y espera a que esté corriendo",
  "Base template (default ubuntu): ubuntu, python, node, code-interpreter…": "Template base (default ubuntu): ubuntu, python, node, code-interpreter…",
  "Human label (lets you `ssh <name>.ghosty`)": "Nombre para personas (permite `ssh <nombre>.ghosty`)",
  "Time to live before auto-destroy (was --timeout)": "Tiempo de vida antes de autodestruirse (antes --timeout)",
  "VM size class (gated by plan)": "Tamaño de la VM (según tu plan)",
  "Environment variable, non-secret (repeatable)": "Variable de entorno, no secreta (repetible)",
  "KEY=VALUE lines (dotenv); - reads stdin. Use it for secrets": "Renglones KEY=VALUE (dotenv); - lee stdin. Úsalo para secretos",
  "Return right away instead of waiting for running": "Regresa de inmediato en vez de esperar a que corra",
  "Show one sandbox": "Muestra un sandbox",
  "Run a shell command inside a sandbox": "Corre un comando de shell dentro de un sandbox",
  "Working directory": "Directorio de trabajo",
  "Kill the command after this long": "Mata el comando después de este tiempo",
  "Read the sandbox journal (optionally one systemd unit)": "Lee el journal del sandbox (opcionalmente de una unit de systemd)",
  "systemd unit to filter": "Unit de systemd a filtrar",
  "Last N lines (default 200)": "Últimos N renglones (default 200)",
  "journalctl time spec, e.g. \"10 min ago\"": "Tiempo en sintaxis de journalctl, p. ej. \"10 min ago\"",
  "Only lines matching": "Sólo los renglones que coincidan",
  "List, read or write files inside a sandbox": "Enlista, lee o escribe archivos dentro de un sandbox",
  "write: inline content instead of a local file": "write: contenido en línea en vez de un archivo local",
  "read: save to a local file (binary-safe)": "read: guarda en un archivo local (seguro con binarios)",
  "Suspend to disk (frees CPU; TTL paused)": "Lo suspende a disco (libera CPU; el TTL se pausa)",
  "Wake a suspended sandbox": "Despierta un sandbox suspendido",
  "Rewrite env on wake, non-secret (repeatable)": "Reescribe el env al despertar, no secreto (repetible)",
  "Destroy a sandbox (irreversible)": "Destruye un sandbox (irreversible)",
  "Skip the confirmation (required without a terminal or with --json)": "Salta la confirmación (obligatorio sin terminal o con --json)",
  "Capture a copy-on-write snapshot without stopping the box": "Toma un snapshot copy-on-write sin detener la caja",
  "Snapshot label": "Nombre del snapshot",
  "Agents running in their own sandbox": "Agentes que corren en su propio sandbox",
  "List your agents": "Enlista tus agentes",
  "Show one agent: record, prompt, MCP servers, skills and files": "Muestra un agente: registro, prompt, servidores MCP, skills y archivos",
  "Only these fields: agentId, name, template, status, lastError, sandboxId, agentUrl, embedToken, createdAt, expiresAt, systemPrompt, systemPromptMode, mcpServers, skills, files": "Sólo estos campos: agentId, name, template, status, lastError, sandboxId, agentUrl, embedToken, createdAt, expiresAt, systemPrompt, systemPromptMode, mcpServers, skills, files",
  "Write the system prompt to a file instead of printing it": "Escribe el system prompt en un archivo en vez de imprimirlo",
  "edit, then: agents set helper --prompt-file PROMPT.md": "edítalo y luego: agents set helper --prompt-file PROMPT.md",
  "Create an agent from a template, or clone one (--like / --from)": "Crea un agente desde un template, o clona uno (--like / --from)",
  "Agent template (see: easybits docs agents)": "Template del agente (ver: easybits docs agents)",
  "Clone another agent's setup: template, prompt, MCP, skills (never its env)": "Clona la configuración de otro agente: template, prompt, MCP, skills (nunca su env)",
  "Clone from `easybits agents export` output": "Clona desde lo que dio `easybits agents export`",
  "Label": "Nombre",
  "System prompt (ghosty-lite, goose)": "System prompt (ghosty-lite, goose)",
  "System prompt from a file": "System prompt desde un archivo",
  "append (default) or replace the engine's prompt": "append (default) o reemplaza el prompt del motor",
  "MCP servers: JSON array or { servers } (ACP templates)": "Servidores MCP: arreglo JSON o { servers } (templates ACP)",
  "--like/--from: also copy the knowledge files in /data/work": "--like/--from: copia también los archivos de conocimiento de /data/work",
  "Env for the agent, non-secret (repeatable)": "Env del agente, no secreto (repetible)",
  "Lifetime before auto-destroy (was --timeout)": "Vida antes de autodestruirse (antes --timeout)",
  "Print the plan; create nothing": "Imprime el plan; no crea nada",
  "Send a message (agent by id or name); streams the reply": "Manda un mensaje (agente por id o nombre); la respuesta llega en streaming",
  "Continue a conversation": "Sigue una conversación",
  "Destroy an agent and its sandbox": "Destruye un agente y su sandbox",
  "asks you to type the id": "te pide teclear el id",
  "Change the system prompt (ghosty-lite, goose); takes effect without a reboot": "Cambia el system prompt (ghosty-lite, goose); entra sin reiniciar",
  "New system prompt": "System prompt nuevo",
  "Read the prompt from a file (- = stdin)": "Lee el prompt de un archivo (- = stdin)",
  "append (to the engine's own) or replace it": "append (al del motor) o lo reemplaza",
  "Show what would change; change nothing": "Enseña qué cambiaría; no cambia nada",
  "Knowledge files in /data/work: list, read, upload (several at once) or delete": "Archivos de conocimiento en /data/work: enlista, lee, sube (varios a la vez) o borra",
  "get: save to a local file (binary-safe)": "get: guarda en un archivo local (seguro con binarios)",
  "put: folder inside /data/work (default: its root)": "put: carpeta dentro de /data/work (default: la raíz)",
  "Skills in /data/agent/skills: list, read, add from a file or folder, remove": "Skills en /data/agent/skills: enlista, lee, agrega desde un archivo o carpeta, quita",
  "add: a single SKILL.md": "add: un solo SKILL.md",
  "add: a folder with SKILL.md and its assets": "add: una carpeta con SKILL.md y sus archivos",
  "add: slug (default: the frontmatter name, else the folder)": "add: slug (default: el name del frontmatter, si no, la carpeta)",
  "get: download the whole skill into this folder": "get: baja la skill entera a esta carpeta",
  "add/rm: restart the agent so it sees the change (new session)": "add/rm: reinicia el agente para que vea el cambio (sesión nueva)",
  "The agent's own MCP servers: show them, or replace the whole list (restarts it)": "Los servidores MCP propios del agente: verlos o reemplazar la lista entera (lo reinicia)",
  "set: JSON array (or { servers }); - = stdin. [] removes all": "set: arreglo JSON (o { servers }); - = stdin. [] quita todos",
  "get: print env/header values unmasked": "get: imprime los valores de env/headers sin tapar",
  "Restart the agent (picks up skills, MCP and prompt mode; starts a new session)": "Reinicia el agente (toma skills, MCP y modo del prompt; abre sesión nueva)",
  "One full turn as text (no stream): verify what you just configured": "Un turno completo como texto (sin streaming): verifica lo que acabas de configurar",
  "Continue this session (printed after each turn)": "Sigue esta sesión (se imprime después de cada turno)",
  "Start a fresh session": "Empieza una sesión nueva",
  "Read the journal of the agent's sandbox": "Lee el journal del sandbox del agente",
  "Check an agent: status, sandbox, prompt, skills frontmatter, MCP; exits 1 on a problem": "Revisa un agente: estado, sandbox, prompt, frontmatter de skills, MCP; sale con 1 si hay un problema",
  "Export an agent as a file you can edit and apply (secrets as ${NAME}, never their value)": "Exporta un agente como archivo que puedes editar y aplicar (secretos como ${NOMBRE}, nunca su valor)",
  "A folder (agent.yaml + skills/ + files/) or a .yaml/.json file": "Una carpeta (agent.yaml + skills/ + files/) o un archivo .yaml/.json",
  "Legacy clone JSON (0.9) with MCP values unmasked": "JSON de clonado de 0.9 con los valores del MCP sin tapar",
  "Legacy clone JSON (0.9) with the file contents": "JSON de clonado de 0.9 con el contenido de los archivos",
  "agent.yaml + skills/ + files/, versionable in git": "agent.yaml + skills/ + files/, versionable en git",
  "after editing: see the plan": "después de editarlo: mira el plan",
  "Make an agent match a file from `agents export` (plan, then apply)": "Hace que un agente coincida con un archivo de `agents export` (plan y luego aplica)",
  "Apply an agent file or folder: shows the plan (+ add, ~ change, - remove, ! skipped), then applies it": "Aplica un archivo o carpeta de agente: enseña el plan (+ agrega, ~ cambia, - quita, ! se salta) y luego lo aplica",
  "Apply to this agent (default: the id in the file)": "Aplicarlo a este agente (default: el id del archivo)",
  "Make a new agent from the file instead": "Crea un agente nuevo desde el archivo",
  "--create: name for the new agent": "--create: nombre del agente nuevo",
  "Also remove what the file doesn't list (env, MCP, skills, files)": "Quita también lo que el archivo no enlista (env, MCP, skills, archivos)",
  "Show the plan; change nothing": "Enseña el plan; no cambia nada",
  "${ANTHROPIC_API_KEY} in the file gets this value": "${ANTHROPIC_API_KEY} del archivo toma este valor",
  "a copy": "una copia",
  "what would be removed": "lo que se quitaría",
  "Hosting": "Hosting",
  "Permanent machines and their releases (easybits deploy <machine> publishes)": "Máquinas permanentes y sus releases (easybits deploy <máquina> publica)",
  "List your permanent machines": "Enlista tus máquinas permanentes",
  "Publish the machine's current app code as a new release": "Publica el código actual de la app como un release nuevo",
  "Release note": "Nota del release",
  "same thing, shorter": "lo mismo, más corto",
  "List releases, newest first": "Enlista los releases, el más nuevo primero",
  "How many": "Cuántos",
  "Tail the app's own log": "Los últimos renglones del log de la app",
  "Last N lines": "Últimos N renglones",
  "Put a previous release back on the same machine (data untouched)": "Vuelve a poner un release anterior en la misma máquina (datos intactos)",
  "App env vars stored encrypted in your vault": "Variables de entorno de la app, cifradas en tu vault",
  "Custom domains with auto TLS on a sandbox or machine": "Dominios propios con TLS automático en un sandbox o máquina",
  "List domains attached to a sandbox": "Enlista los dominios de un sandbox",
  "Attach a domain to a port; prints the DNS record to create": "Liga un dominio a un puerto; imprime el registro DNS que hay que crear",
  "Port inside the sandbox (required)": "Puerto dentro del sandbox (obligatorio)",
  "Check DNS + HTTPS for a domain": "Revisa DNS + HTTPS de un dominio",
  "Detach a domain": "Desliga un dominio",
  "Write the GitHub Actions deploy workflow for this repo": "Escribe el workflow de GitHub Actions que despliega este repo",
  "Write the GitHub Actions workflow that deploys this repo on every push to main": "Escribe el workflow de GitHub Actions que despliega este repo en cada push a main",
  "Where the app lives in the machine (default /srv/app)": "Dónde vive la app en la máquina (default /srv/app)",
  "Port your app listens on (default 3000)": "Puerto en el que escucha tu app (default 3000)",
  "Data": "Datos",
  "SQL databases (libSQL)": "Bases de datos SQL (libSQL)",
  "List your databases": "Enlista tus bases de datos",
  "Create a database": "Crea una base de datos",
  "What it is for": "Para qué es",
  "Delete a database (irreversible)": "Borra una base de datos (irreversible)",
  "asks you to type the name": "te pide teclear el nombre",
  "scripts and agents": "scripts y agentes",
  "List tables with row counts and columns": "Enlista las tablas con su número de filas y columnas",
  "Run one SQL statement (by database id or name)": "Corre una sentencia SQL (por id o nombre de la base)",
  "Positional ? parameter (repeatable)": "Parámetro ? posicional (repetible)",
  "Storage": "Almacenamiento",
  "Your files in EasyBits storage": "Tus archivos en el almacenamiento de EasyBits",
  "List your files": "Enlista tus archivos",
  "Upload a local file": "Sube un archivo local",
  "Delete a file (soft delete, 7-day trash)": "Borra un archivo (a la papelera 7 días)",
  "List your static websites": "Enlista tus sitios estáticos",
  "Show storage providers": "Muestra los proveedores de almacenamiento",
  "MCP": "MCP",
  "Print the MCP config JSON for your agent or editor": "Imprime el JSON de configuración MCP para tu agente o editor",
  "Print MCP config JSON: streamable HTTP with your key, or stdio (npx @easybits.cloud/mcp)": "Imprime el JSON de configuración MCP: streamable HTTP con tu key, o stdio (npx @easybits.cloud/mcp)",
  "stdio config (npx @easybits.cloud/mcp) instead of streamable HTTP": "Configuración stdio (npx @easybits.cloud/mcp) en vez de streamable HTTP",
  "SSH": "SSH",
  "Print your public key for sandbox SSH (creates it once)": "Imprime tu llave pública para SSH a un sandbox (la crea una vez)",
  "Print your public key for sandbox_ssh_enable (creates ~/.ssh/easybits_ed25519 once)": "Imprime tu llave pública para sandbox_ssh_enable (crea ~/.ssh/easybits_ed25519 una vez)",
  "SSH tunnel over 443 (use as ssh ProxyCommand)": "Túnel SSH por el 443 (úsalo como ProxyCommand de ssh)",
  "SSH tunnel over 443; meant to be the ProxyCommand in ~/.ssh/config": "Túnel SSH por el 443; pensado como el ProxyCommand de ~/.ssh/config",
  "with the ~/.ssh/config snippet from `easybits --help`": "con el bloque de ~/.ssh/config de `easybits --help`",
  "Help": "Ayuda",
  "Print the docs URL, or a docs section as markdown": "Imprime la URL de los docs, o una sección de los docs en markdown",
  "English docs": "Docs en inglés",
  "Open the docs in your browser": "Abre los docs en tu navegador",
  "Shell completion script (zsh, bash, fish)": "Script de autocompletado para tu shell (zsh, bash, fish)",
  "Print the completion script for your shell: commands, flags and your agents, sandboxes and databases": "Imprime el script de autocompletado de tu shell: comandos, flags y tus agentes, sandboxes y bases",
  "add to ~/.zshrc, after compinit": "agrégalo a ~/.zshrc, después de compinit",
  "add to ~/.bashrc": "agrégalo a ~/.bashrc",
};
